ALTER TABLE Users DROP FOREIGN KEY fkcUsers1;
ALTER TABLE Groups DROP FOREIGN KEY fkcGroups1;
ALTER TABLE Rooms DROP FOREIGN KEY fkcRooms1;
ALTER TABLE Bookings DROP FOREIGN KEY fkcBookings1;
ALTER TABLE Bookings DROP FOREIGN KEY fkcBookings2;
ALTER TABLE Bookings DROP FOREIGN KEY fkcBookings3;
ALTER TABLE GroupUserXR DROP FOREIGN KEY fkcGroupUserXR1;
ALTER TABLE GroupUserXR DROP FOREIGN KEY fkcGroupUserXR2;

DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Groups;
DROP TABLE IF EXISTS Buildings;
DROP TABLE IF EXISTS Rooms;
DROP TABLE IF EXISTS Bookings;
DROP TABLE IF EXISTS Timeslots;
DROP TABLE IF EXISTS GroupUserXR;